devices:
  192.168.44.123:
    name: StripTV
    transition: 1000
    nightlight_switch_type: light
    #model: yeelink.yeelight_strip6
  192.168.44.20:
    name: StripPC
    transition: 1000
    nightlight_switch_type: light
    #model: yeelink.light.strip1
